# Generated by Django 2.2.1 on 2019-06-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID_Client', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Entreprise', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Tel', models.CharField(max_length=25)),
                ('Adresse', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('ID_Commande', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Date_Commande', models.DateField()),
                ('ID_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('ID_Depot', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=25)),
                ('Adresse', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('ID_Fournisseur', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Entreprise', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Tel', models.CharField(max_length=25)),
                ('Adresse', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ID_Article', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=25)),
                ('Photo', models.ImageField(upload_to='articles')),
                ('Prix_Unitaire', models.FloatField()),
                ('ID_Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('ID_Administrateur', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=25)),
                ('Nom', models.CharField(max_length=25)),
                ('Prenom', models.CharField(max_length=25)),
                ('Genre', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Tel', models.CharField(max_length=25)),
                ('Photo', models.ImageField(upload_to='admins')),
                ('ID_Depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Depot')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.IntegerField()),
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Article')),
                ('ID_Depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Depot')),
            ],
            options={
                'unique_together': {('ID_Depot', 'ID_Article')},
            },
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.IntegerField()),
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Article')),
                ('ID_Commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Commande')),
            ],
            options={
                'unique_together': {('ID_Commande', 'ID_Article')},
            },
        ),
    ]
