# Generated by Django 2.2.1 on 2019-06-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('ID_Devis', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Date_Commande', models.DateField()),
                ('ID_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DetailDevis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.IntegerField()),
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Article')),
                ('ID_Devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Commande')),
            ],
            options={
                'unique_together': {('ID_Devis', 'ID_Article')},
            },
        ),
    ]
