# Generated by Django 2.2.1 on 2019-06-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190607_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildevis',
            name='ID_Devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Devis'),
        ),
    ]
