# Generated by Django 2.2.1 on 2019-06-08 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_administrateur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Date_Commande',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
