# Generated by Django 2.2.1 on 2019-06-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190608_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcommande',
            name='Prix',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
