# Generated by Django 2.2.1 on 2019-06-08 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190608_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='Chauffeur',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='Date_Sortie',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='devis',
            name='Matricule',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='Transport',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='Type_Transport',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
