# Generated by Django 2.2.1 on 2019-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20190608_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaildevis',
            name='Prix',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
